version: '3.5'
services:
  command-mediator-mq:
    container_name: rabbitmq-command-mediator
    image: rabbitmq:3-management-alpine
    volumes:
      - rmq-data:/var/lib/rabbitmq/
      - rmq-log:/var/log/rabbitmq/
    networks:
      - macnet
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - macnet
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data


  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    # For better performance, consider `host` mode instead `port` to avoid docker NAT.
    # `host` mode is NOT currently supported in Swarm Mode.
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode
    # network_mode: "host"
    networks:
      - macnet
    volumes:
      - dragonflydata:/data


 #  strapi:
 #   image: naskio/strapi
 #   environment:
 #     NODE_ENV: development # or production
 #   networks:
 #     - macnet
 #   ports:
 #     - "1337:1337"
 #   # volumes:
 #   #   - ./app:/srv/app # mount an existing strapi project

volumes:
  rmq-data:
  rmq-log:
  minio_storage:
  dragonflydata:


networks:
  macnet:
    external: true
    name: drktest0
